-- Create the transactions table
create table transactions (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  text text not null,
  amount numeric not null,
  category text not null,
  date text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Set up Row Level Security (RLS)
alter table transactions enable row level security;

-- Create policies and restrict access to the logged-in user
create policy "Individuals can create their own transactions." on transactions for
    insert with check (auth.uid() = user_id);

create policy "Individuals can view their own transactions. " on transactions for
    select using (auth.uid() = user_id);

create policy "Individuals can delete their own transactions." on transactions for
    delete using (auth.uid() = user_id);
